### ISSUE TITLE
Column Class not Working

### ISSUE THREAD

**Issue by wchisenski** [cunhapaulo/marpstyle#4]
**Thank you for making some great Marp themes!**

In the examples you utilize the following code to generate two columns of text _(specifically lists)_:

```html
<div class="columns">
<div>

1. Item
2. Item
3. Item

</div>
<div>

4. Item
5. Item
6. Item

</div>
</div>
```

When looking at your PDF output, this rendered two columns within the slide. Although when I download your Markdown example file `example-einstein.md` it does not render correctly using the Marp extension within VS Code or when I export to PDF.

Any assistance would be helpful, thank you!

**Comment by cunhapaulo** [comment]
Hope you've found the right solution.

**Comment by wchisenski** [comment]
Hi @cunhapaulo,

Apologies for the delay in this reply. Yes, the link you provided did help me resolve the issue. Why not simply include the column class needed in your CSS theme files instead of requiring users to put the following in their YAML front matter?

```css
style: |
  .columns {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 1rem;
  }
```
